### ISSUE TITLE
Bid requests get blocked on https sites

### ISSUE THREAD

**Issue by ix-certification** [indexexchange/improve-digital-adapter#3]
Browser.getProtocol() will return the value of "https:" instead of "https" as a result bid requests are getting blocked by the browser.

Additionally, from what we can see is that to access the constant "SECURE" & "STANDARD", there is another level that is missing in the object which is supposed to be  __adServerClient.CONSTANTS.HTTP_SECURITY.SECURE

https://github.com/indexexchange/improve-digital-adapter/blob/adccd718df4663e5dafe96c09f8df5e664b557ac/improve-digital-htb.js#L171

Test page: https://sandbox.ht.indexexchange.com/ht/improvedigital-test.html

**Comment by agregorio-improve** [comment]
Fixed

**Comment by ix-certification** [comment]
The PR has been accepted & merged
