### ISSUE TITLE
Double invoking of strict mode  

### ISSUE THREAD

**Issue by ix-certification** [indexexchange/improve-digital-adapter#4]
One of the 'use stricts' can be removed 

https://github.com/indexexchange/improve-digital-adapter/blob/master-v2/improve-digital-htb.js#L513

**Comment by agregorio-improve** [comment]
Done!

**Comment by ix-certification** [comment]
@agregorio-improve can we please create a PR for this.

**Comment by ix-certification** [comment]
The PR has been accepted & merged
