### ISSUE TITLE
Uninitialized variable within a loop

### ISSUE THREAD

**Issue by ix-certification** [indexexchange/improve-digital-adapter#6]
Since JavaScript hoists variables up to the top of the function, if a variable is declared inside a `for` loop and is not set to a safe empty value, future iterations of the loop will use the previous iteration's value. This can lead to incorrect targeting and discrepancy.

https://github.com/indexexchange/improve-digital-adapter/blob/master-v2/improve-digital-htb.js#L314

**Comment by agregorio-improve** [comment]
Fixed

**Comment by ix-certification** [comment]
@agregorio-improve 

Thanks for the update. Once the PR has been created, we can review the code and merge it.
